# Generated by Django 4.2.7 on 2025-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0003_alter_aprendizcurso_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
