# Generated by Django 5.2.5 on 2025-08-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aprendices", "0003_alter_aprendizcurso_options_alter_curso_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TEO", "Teórica"),
                            ("PRA", "Práctica"),
                            ("PRO", "Proyecto"),
                        ],
                        default="TEO",
                        max_length=3,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField()),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("REA", "Realizada"),
                            ("COR", "Corregida"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="aprendices.aprendiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "ordering": ["-fecha"],
            },
        ),
    ]
