# Generated by Django 4.2.7 on 2025-12-29 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0004_alter_aprendiz_ciudad_alter_aprendiz_correo_and_more'),
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='aprendices.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='aprendices.aprendiz', verbose_name='Aprendiz'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('REA', 'Realizada'), ('COR', 'Corregida')], default='PEN', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('TEO', 'Teórica'), ('PRA', 'Práctica'), ('PRO', 'Proyecto')], default='TEO', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['-fecha'], name='evaluacione_fecha_d17359_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['aprendiz', 'curso'], name='evaluacione_aprendi_7a0787_idx'),
        ),
    ]
